import type { APIRoute, GetStaticPaths } from "astro";

export const getStaticPaths: GetStaticPaths = () => {
  const rivers = [
    "ganga",
    "yamuna",
    "saraswati",
    "krishna",
    "kaveri",
    "godavari",
    "brahmaputra",
    "narmada",
    "indus",
    "mahanadi",
  ];

  return rivers.map((river) => ({
    params: { river },
  }));
};

export const GET: APIRoute = async ({ params }) => {
  const river = params.river;

  // In a real implementation, you would generate a comprehensive PDF here
  const pdfContent = `
    ${river?.toUpperCase()} - Sacred River Information
    
    Generated by nadistuti.com
    
    This would contain:
    - Detailed geographical information
    - Complete list of tributaries
    - Cultural and religious significance
    - Historical references
    - Maps and images
    - Sanskrit verses and translations
    
    [This is a demo PDF - In production, this would be a properly formatted PDF document]
  `;

  return new Response(pdfContent, {
    status: 200,
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${river}-information.pdf"`,
    },
  });
};
